// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Mon May 31 12:06:07 2021

RLE_Dumb_System RLE_Dumb_System_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.pixelin(pixelin_sig) ,	// input [23:0] pixelin_sig
	.pixelout(pixelout_sig) ,	// output [23:0] pixelout_sig
	.im_reset(im_reset_sig) ,	// output  im_reset_sig
	.stream1(stream1_sig) ,	// output [9:0] stream1_sig
	.stream2(stream2_sig) ,	// output [9:0] stream2_sig
	.stream3(stream3_sig) 	// output [9:0] stream3_sig
);

